pipeline:

  build:
    image: ukhomeoffice/drone-docker
    repo: quay.io/ukhomeofficedigital/dq-nats-historical-processing
    secrets: [ docker_username, docker_password ]
    registry: quay.io
    context: app
    dockerfile: app/Dockerfile
    force_tag: true
    tags:
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_BUILD_NUMBER}
    when:
      event: push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    environment:
      - KUBE_NAMESPACE=dq-apps-notprod
      - INSECURE_SKIP_TLS_VERIFY=true
      - NATS_PVC_SIZE=1Gi
      - NATS_CPU_REQUEST=1
      - NATS_CPU_LIMIT=1.5
      - NATS_RAM_REQUEST=1Gi
      - NATS_RAM_LIMIT=1.5Gi
    commands:
      - export KUBE_TOKEN=$$NOTPROD_KUBE_TOKEN
      - export KUBE_SERVER=$$NOTPROD_KUBE_SERVER
      - export S3_REGION_NAME=$$S3_REGION_NAME
      - export BATCH_SIZE=$$NOTPROD_BATCH_SIZE
      - export S3_SRC_BUCKET_NAME=$$NOTPROD_S3_SRC_BUCKET_NAME
      - export S3_SRC_KEY_PREFIX=$$NOTPROD_S3_SRC_KEY_PREFIX
      - export S3_SRC_KEY_PREFIX_1=$$NOTPROD_S3_SRC_KEY_PREFIX_1
      - export S3_SRC_KEY_PREFIX_2=$$NOTPROD_S3_SRC_KEY_PREFIX_2
      - export S3_SRC_KEY_PREFIX_3=$$NOTPROD_S3_SRC_KEY_PREFIX_3
      - export S3_SRC_KEY_PREFIX_4=$$NOTPROD_S3_SRC_KEY_PREFIX_4
      - export S3_SRC_KEY_PREFIX_5=$$NOTPROD_S3_SRC_KEY_PREFIX_5
      - export S3_SRC_KEY_PREFIX_6=$$NOTPROD_S3_SRC_KEY_PREFIX_6
      - export S3_SRC_KEY_PREFIX_7=$$NOTPROD_S3_SRC_KEY_PREFIX_7
      - export S3_SRC_ACCESS_KEY_ID=$$NOTPROD_S3_SRC_ACCESS_KEY_ID
      - export S3_SRC_SECRET_ACCESS_KEY=$$NOTPROD_S3_SRC_SECRET_ACCESS_KEY
      - export S3_DST_BUCKET_LOCATION=$$NOTPROD_S3_DST_BUCKET_LOCATION
      - export S3_DST_ACCESS_KEY_ID=$$NOTPROD_S3_DST_ACCESS_KEY_ID
      - export S3_DST_SECRET_ACCESS_KEY=$$NOTPROD_S3_DST_SECRET_ACCESS_KEY
      - export SLACK_WEBHOOK=$$NOTPROD_SLACK_WEBHOOK
      - kd -f kube/pvc.yml -f kube/secret.yml
      - kd --replace -f kube/job.yml
    secrets:
      - NOTPROD_KUBE_TOKEN
      - NOTPROD_KUBE_SERVER
      - S3_REGION_NAME
      - NOTPROD_BATCH_SIZE
      - NOTPROD_S3_SRC_BUCKET_NAME
      - NOTPROD_S3_SRC_KEY_PREFIX
      - NOTPROD_S3_SRC_KEY_PREFIX_1
      - NOTPROD_S3_SRC_KEY_PREFIX_2
      - NOTPROD_S3_SRC_KEY_PREFIX_3
      - NOTPROD_S3_SRC_KEY_PREFIX_4
      - NOTPROD_S3_SRC_KEY_PREFIX_5
      - NOTPROD_S3_SRC_KEY_PREFIX_6
      - NOTPROD_S3_SRC_KEY_PREFIX_7
      - NOTPROD_S3_SRC_ACCESS_KEY_ID
      - NOTPROD_S3_SRC_SECRET_ACCESS_KEY
      - NOTPROD_S3_DST_BUCKET_LOCATION
      - NOTPROD_S3_DST_ACCESS_KEY_ID
      - NOTPROD_S3_DST_SECRET_ACCESS_KEY
      - NOTPROD_SLACK_WEBHOOK
    when:
      event: push

  deploy_to_production:
    image: quay.io/ukhomeofficedigital/kd
    environment:
      - KUBE_NAMESPACE=dq-apps
      - INSECURE_SKIP_TLS_VERIFY=true
      - NATS_PVC_SIZE=5Gi
      - NATS_CPU_REQUEST=2
      - NATS_CPU_LIMIT=2.5
      - NATS_RAM_REQUEST=3Gi
      - NATS_RAM_LIMIT=4Gi
    commands:
      - export KUBE_TOKEN=$$PROD_KUBE_TOKEN
      - export KUBE_SERVER=$$PROD_KUBE_SERVER
      - export S3_REGION_NAME=$$S3_REGION_NAME
      - export BATCH_SIZE=$$PROD_BATCH_SIZE
      - export S3_SRC_BUCKET_NAME=$$PROD_S3_SRC_BUCKET_NAME
      - export S3_SRC_KEY_PREFIX=$$PROD_S3_SRC_KEY_PREFIX
      - export S3_SRC_KEY_PREFIX_1=$$PROD_S3_SRC_KEY_PREFIX_1
      - export S3_SRC_KEY_PREFIX_2=$$PROD_S3_SRC_KEY_PREFIX_2
      - export S3_SRC_KEY_PREFIX_3=$$PROD_S3_SRC_KEY_PREFIX_3
      - export S3_SRC_KEY_PREFIX_4=$$PROD_S3_SRC_KEY_PREFIX_4
      - export S3_SRC_KEY_PREFIX_5=$$PROD_S3_SRC_KEY_PREFIX_5
      - export S3_SRC_KEY_PREFIX_6=$$PROD_S3_SRC_KEY_PREFIX_6
      - export S3_SRC_KEY_PREFIX_7=$$PROD_S3_SRC_KEY_PREFIX_7
      - export S3_SRC_ACCESS_KEY_ID=$$PROD_S3_SRC_ACCESS_KEY_ID
      - export S3_SRC_SECRET_ACCESS_KEY=$$PROD_S3_SRC_SECRET_ACCESS_KEY
      - export S3_DST_BUCKET_LOCATION=$$PROD_S3_DST_BUCKET_LOCATION
      - export S3_DST_ACCESS_KEY_ID=$$PROD_S3_DST_ACCESS_KEY_ID
      - export S3_DST_SECRET_ACCESS_KEY=$$PROD_S3_DST_SECRET_ACCESS_KEY
      - export SLACK_WEBHOOK=$$PROD_SLACK_WEBHOOK
      - kd -f kube/pvc.yml -f kube/secret.yml
      - kd --replace -f kube/job.yml
    secrets:
      - PROD_KUBE_TOKEN
      - PROD_KUBE_SERVER
      - S3_REGION_NAME
      - PROD_BATCH_SIZE
      - PROD_S3_SRC_BUCKET_NAME
      - PROD_S3_SRC_KEY_PREFIX
      - PROD_S3_SRC_KEY_PREFIX_1
      - PROD_S3_SRC_KEY_PREFIX_2
      - PROD_S3_SRC_KEY_PREFIX_3
      - PROD_S3_SRC_KEY_PREFIX_4
      - PROD_S3_SRC_KEY_PREFIX_5
      - PROD_S3_SRC_KEY_PREFIX_6
      - PROD_S3_SRC_KEY_PREFIX_7
      - PROD_S3_SRC_ACCESS_KEY_ID
      - PROD_S3_SRC_SECRET_ACCESS_KEY
      - PROD_S3_DST_BUCKET_LOCATION
      - PROD_S3_DST_ACCESS_KEY_ID
      - PROD_S3_DST_SECRET_ACCESS_KEY
      - PROD_SLACK_WEBHOOK
    when:
      environment: production
      branch: master
      event: deployment
