---
apiVersion: v1
kind: Secret
metadata:
  name: dq-nats-historical-processing
type: Opaque
data:
  S3_REGION_NAME: {{.S3_REGION_NAME}}
  BATCH_SIZE: {{.BATCH_SIZE}}
  S3_SRC_BUCKET_NAME: {{.S3_SRC_BUCKET_NAME}}
  S3_SRC_KEY_PREFIX: {{.S3_SRC_KEY_PREFIX}}
  S3_SRC_ACCESS_KEY_ID: {{.S3_SRC_ACCESS_KEY_ID}}
  S3_SRC_SECRET_ACCESS_KEY: {{.S3_SRC_SECRET_ACCESS_KEY}}
  S3_DST_BUCKET_LOCATION: {{.S3_DST_BUCKET_LOCATION}}
  S3_DST_ACCESS_KEY_ID: {{.S3_DST_ACCESS_KEY_ID}}
  S3_DST_SECRET_ACCESS_KEY: {{.S3_DST_SECRET_ACCESS_KEY}}
  SLACK_WEBHOOK: {{.SLACK_WEBHOOK}}
